repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --check --settings-file config/.isort.cfg .
        language: system
        types: [python]
        pass_filenames: false

      - id: black
        name: black
        entry: black --check --diff --config config/.black .
        language: system
        types: [python]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 --config config/.flake8 .
        language: system
        types: [python]
        pass_filenames: false
