version: '3'

services:
  speech_to_text_bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: speech_to_text_bot
    container_name: speech_to_text_bot
    env_file:
      - .env
    volumes:
      - ${LOGS_PATH}:/app/logs
    restart: unless-stopped