version: '3'

services:
  speech_to_text_bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: speech_to_text_bot
    container_name: speech_to_text_bot
    environment:
      - TOKEN=YOUR-TOKEN
      - SERVER_HOST=YOUR-SERVER-HOST
      - SERVER_PORT=YOUR-SERVER-PORT
    volumes:
      - YOUR-PATH:/app/logs
    restart: unless-stopped